### ISSUE TITLE
socket.emit(err) instead of console.error

### ISSUE THREAD

**Issue by rgbkrk** [n-riesco/jmp#11]
When there's an error, jmp currently logs to the console. It should rely on emitting an 'error'.

**Comment by n-riesco** [comment]
https://nodejs.org/api/events.html#events_error_events

> If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.

**Comment by n-riesco** [comment]
These are my thoughts on this issue:
- Emitting "error" instead of using `console.error` would force users to register an "error" listener (in most cases, just to drop the "error" event).
- I realise that the use of `console.error` [here](https://github.com/n-riesco/jmp/blob/master/index.js#L169), [here](https://github.com/n-riesco/jmp/blob/master/index.js#L176) and [here](https://github.com/n-riesco/jmp/blob/master/index.js#L193) is noisy. I will silence them by guarding them with an `if (DEBUG) {...}`.

**Comment by rgbkrk** [comment]
I... actually assumed there would be an error event since it was an event emitter. 

Definitely a fan of the `DEBUG` block. A lot of node devs use [`debug`](https://github.com/visionmedia/debug) within their packages for handling this.

**Comment by n-riesco** [comment]
Thx for the tip. Although, I'd like to keep JMP's direct dependencies to a minimum, I'll make the code `debug` friendly.

**Comment by n-riesco** [comment]
For the record, a few more references on handling of malformed messages:
- Drop malformed messages:
  - https://github.com/zeromq/libzmq/issues/46
  - http://zguide.zeromq.org/page:all
    
    > The APIs don't do any error reporting. If something isn't as expected, they raise an assertion (or exception depending on the language). This is ideal for a reference implementation, so any protocol errors show immediately. For real applications, the API should be robust against invalid messages.
- Assert malformed messages:
  - http://zguide.zeromq.org/page:all
    
    > Tester receives invalid message (and asserts as designed)

**Comment by rgbkrk** [comment]
> Although, I'd like to keep JMP's direct dependencies to a minimum, I'll make the code debug friendly.

Definitely a good sentiment

**Comment by n-riesco** [comment]
@rgbkrk [Here](https://github.com/n-riesco/jmp/commit/435fbf116492022ff3c4b904c3ff45ca4fba75a2)'s how I propose to do the logging. What do you think?

**Comment by rgbkrk** [comment]
Since the noop is there, this certainly works for my original concern. I wanted to be able to filter on the error streams and handle them programmatically (in case I need to display an error to the user or ignore it). This at least squashes things so it won't be noisy to the end user.

**Comment by rgbkrk** [comment]
I see why you [wouldn't want to emit an error now, as it would likely close the socket](https://nodejs.org/api/net.html#net_event_error_1).

**Comment by n-riesco** [comment]
I've just realised that this commit wouldn't play well with the `--debug` flag in IJavascript.

We should so something like this instead:

``` js
var DEBUG = global.DEBUG || false;

var log;
if (DEBUG) {
    var console = require("console");
    log = function log() {
        process.stderr.write("JMP: ");
        console.error.apply(this, arguments);
    };
} else {
    try {
        log = require("debug")("JMP:");
    } catch (err) {
        log = function noop() {};
}
```
