### ISSUE TITLE
If `require("zmq")` fails, try to rebuild `zmq`

### ISSUE THREAD

**Issue by n-riesco** [n-riesco/jmp#15]
Moved from https://github.com/n-riesco/ijavascript/issues/76

**Comment by rgbkrk** [comment]
https://github.com/juliangruber/require-rebuild Might be worth experimenting with

**Comment by n-riesco** [comment]
@rgbkrk Oh! In that case, I should move this issue back to IJavascript.

**Comment by lgeiger** [comment]
Since we are using https://github.com/zeromq/zeromq.js this can be closed 🎉

**Comment by n-riesco** [comment]
I've reopened this issue in the IJavascript repositiory. I'm now convinced IJavascript is reponsible for a solution.

@lgeiger `zeromq` doesn't solve this issue, does it? If the node version changes `zeromq` needs rebuilding.

**Comment by rgbkrk** [comment]
That's correct, the onus is on the user to reinstall globally installed modules to use the current version. This _can_ be detected to inform the user and it should be done within a client facing application (not a library). My suggestion there would be for ijavascript to provide a good error message, possibly even with a link to an issue or documentation.

For instance, in the nteract notebook we do roughly the following with a top level `try` `catch`:

``` js
switch(err.code) {
  case 'MODULE_NOT_FOUND':
    const msgEl = document.createElement('pre');
    msgEl.textContent = 'Do you need to npm install any new packages?';
    msgContainer.appendChild(msgEl);
    break;
  default:
    if(/Module version mismatch/.test(err.message)) {
      msgContainer.innerHTML = '<p>nteract\'s native modules mismatch, try running <a href="https://github.com/nteract/nteract#troubleshooting"><pre>npm run reinstall</pre></a> from the root of the git clone</p>';
  }
}
```
