### ISSUE TITLE
Exporting `zmq`

### ISSUE THREAD

**Issue by n-riesco** [n-riesco/jmp#2]
@rgbkrk and  @willwhitney

I've just refactored the IJavascript kernel to use `jmp`. At the moment, the kernel requires both `zmq` and `jmp`, i.e:

``` javascript
var zmq = require("zmq");
var jmp = require("jmp");
```

This also means I have to declare both `zmq` and `jmp` as dependencies in `package.json`.
Since `jmp` is a thin wrapper around `zmq`, I'm considering the possibility of exporting `zmq` from `jmp`, so that the following is possible:

``` javascript
var jmp = require("jmp");
var zmq = jmp.zmq;
```

and `package.json` would only declare `jmp` as a dependency.

I haven't come up with any arguments against this change. Would it cause you any problems?

**Comment by willwhitney** [comment]
That sounds fine, but honestly the best solution seems like it would be to
move absolutely all of the `zmq` usage from the kernel into `jmp`. That way
`jmp` would completely encapsulate all needed communication with the
clients.

**Comment by n-riesco** [comment]
That means moving the heartbeat socket too (which is an echo server).

I thought importing `zmq` into `jmp` was the simplest approach.

An alternative approach would be to modify `jmp.Message` to keep a copy of the message before parsing (so that I can implement the echo server).

**Comment by willwhitney** [comment]
My ideal situation would be to have `jmp` implement 100% of the communication between a kernel and a client, heartbeat included. The project using `jmp` would then not need to know anything about the Jupyter protocol at all.

Instead, `jmp` could expose an event that could be subscribed to with something like 

``` javascript
jmp.on('disconnected', function() {})
```

Really, the overall API I'm proposing would be higher-level than what's in `jmp` right now. The dream would be 

``` javascript
jmp.on('execute_request', function(requestObject) {})
jmp.on('complete_request', function(requestObject) {})
jmp.on('inspect_request', function(requestObject) {})
```

etc.

But maybe that's a conversation for a different day — this is already a great start.

As far as whether to export `zmq`, that sounds fine to me. If the package using `jmp` needs another version of `zmq` or something they can still require it separately.
