### ISSUE TITLE
Implement request

### ISSUE THREAD

**Issue by rgbkrk** [n-riesco/jmp#5]
Currently respond is there, but no way to do an initial request. For example, I'd like to be able to send a `kernel_info_request` on the `SHELL` channel.

**Comment by n-riesco** [comment]
I meant to come back to you on this today, but it looks like I won't find the time. Is this urgent for you?

I was planning to write some test for this package and see what it needs to be done to build an initial request.

I'm open to suggestions :)

**Comment by rgbkrk** [comment]
I hacked together what I needed directly but I'm running into troubles where it seems like it's only responding with the delimiter:

https://github.com/rgbkrk/jupyter-sidecar/pull/32

https://github.com/rgbkrk/jupyter-sidecar/pull/32/files#diff-ac3510bf980f81aed681d03935e8fe2eR67

I was also happy posting this as an issue to express interest before I do it myself when I have the time and energy.

**Comment by n-riesco** [comment]
See #6
